# Generated by Django 5.0.4 on 2024-05-18 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('resumo', models.TextField()),
                ('palavras_chave', models.CharField(max_length=100)),
                ('data_entrega', models.DateField()),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('area_concentracao', models.CharField(blank=True, max_length=100, null=True)),
                ('arquivos', models.FileField(upload_to='arquivos/')),
                ('autor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monografia_escrita', to=settings.AUTH_USER_MODEL)),
                ('banca_examinadora', models.ManyToManyField(related_name='monografias_banca', to=settings.AUTH_USER_MODEL, verbose_name='Banca Examinadora')),
                ('coorientador', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orientador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monografias_orientadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
