# Generated by Django 5.0.4 on 2024-04-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('orientador', models.CharField(max_length=100)),
                ('coorientador', models.CharField(blank=True, max_length=100, null=True)),
                ('resumo', models.TextField()),
                ('palavras_chave', models.CharField(max_length=100)),
                ('data_entrega', models.DateField()),
                ('banca_examinadora', models.CharField(blank=True, max_length=100, null=True)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('area_concentracao', models.CharField(blank=True, max_length=100, null=True)),
                ('arquivo', models.FileField(upload_to='monografias/%Y/%m/%d')),
            ],
        ),
    ]
