# Generated by Django 5.0.4 on 2024-04-25 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monografias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monografia',
            old_name='arquivo',
            new_name='arquivos',
        ),
    ]
