# Generated by Django 5.0.4 on 2024-06-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisador',
            name='nivel',
            field=models.CharField(choices=[('Graduação', 'Graduacao'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], max_length=10, verbose_name='Titulação'),
        ),
    ]
