# Generated by Django 5.0.4 on 2024-06-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0002_alter_pesquisador_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisador',
            name='cargo',
            field=models.CharField(choices=[('Aluno', 'Aluno'), ('Professor', 'Professor'), ('Administrador', 'Admnistrador')], max_length=15, verbose_name='Cargo'),
        ),
    ]
